### ISSUE TITLE
Create default admin

### ISSUE THREAD

**Issue by mycwnet** [Aye-Bee-See/sqlite-express-api#5]
Create a default admin user on creation

**Comment by paxblueribbon** [comment]
We should remove the jwt that is in the public repo under postman tests while we're at it, get it to request and use this live like we do in the auth test get request

**Comment by mycwnet** [comment]
Is that part of creating a default admin?

**Comment by mycwnet** [comment]
So the current code in the branch is functional though user ids need to be something probably different from an integer and idk what the default credentials should be but it's easily changeable and building seeds if necessary for other tables should be fairly simple.
